import { chromium } from 'playwright';
import fs from 'node:fs';
const OUT='/tmp/livecheck-165/out'; const DUR=132000;
const reqs=[],nonGet=[],wsEvents=[];
const b=await chromium.launch();
const ctx=await b.newContext({viewport:{width:1400,height:900}});
const p=await ctx.newPage();
p.on('request',r=>{const e={method:r.method(),url:r.url(),t:Date.now()};reqs.push(e);if(r.method()!=='GET')nonGet.push(e);});
p.on('websocket',ws=>{const t0=Date.now();wsEvents.push({ev:'ws-create',url:ws.url(),t:t0});ws.on('close',()=>wsEvents.push({ev:'ws-close',t:Date.now()}));ws.on('framereceived',()=>wsEvents.push({ev:'ws-frame-in',t:Date.now()}));});
await p.route('**/api/**',async r=>{if(r.request().method()!=='GET')return r.abort();return r.continue();});
await p.goto('http://127.0.0.1:8081/',{waitUntil:'domcontentloaded'});
await p.waitForFunction(()=>document.querySelector('[data-viewport-fit]')!==null,null,{timeout:25000}).catch(()=>{});
const t0=Date.now(); const mark=reqs.length;
await p.waitForTimeout(DUR);
const q=u=>{try{return Object.fromEntries(new URL(u).searchParams);}catch{return{};}};
const win=reqs.slice(mark);
const fb=win.filter(r=>r.method==='GET'&&r.url.includes('/api/kline')&&!r.url.includes('before=')&&q(r.url).limit==='5').map(r=>({t:r.t,rel:r.t-t0}));
const ws=wsEvents.filter(e=>e.t>=t0).map(e=>({ev:e.ev,rel:e.t-t0,url:e.url}));
const out={shanghai:new Date(t0+8*3600*1000).toISOString().replace('T',' ').slice(0,19)+' +08',durationSec:DUR/1000,visibilityState:await p.evaluate(()=>document.visibilityState),nonGetTotal:nonGet.length,fallbackCount:fb.length,fallback:fb.map(x=>({rel:x.rel,iso:new Date(x.t).toISOString()})),fallbackRawTs:fb.map(x=>x.t),wsEvents:ws,wsOpens:ws.filter(e=>e.ev==='ws-create').length,wsCloses:ws.filter(e=>e.ev==='ws-close').length,wsFramesIn:ws.filter(e=>e.ev==='ws-frame-in').length,methodsSeen:[...new Set(reqs.map(r=>r.method))]};
fs.writeFileSync(OUT+'/observe3.json',JSON.stringify(out,null,2));
console.log(JSON.stringify(out,null,1));await b.close();
