import subprocess, datetime, sys
RM='/home/eestock/workspace/git/eestock/eestock-rs'
EV=f'{RM}/tester/evidence/268_d53/05_hygiene.txt'
def sh(c, env=None):
    import os
    e=dict(os.environ); e.update(env or {})
    return subprocess.run(c, shell=True, cwd=RM, capture_output=True, text=True, env=e).stdout.strip()
PAT='[v]ites[t]|[c]heck-tangl[e]|[c]argo tes[t]|[r]ust_prob[e]|[p]arity_prob[e]'
L=[]
L.append("# D5-3 独立验收证据 ⑤：卫生（共享库键 / staged / 进程与端口 / 归因）")
L.append(f"## 生成时间: {datetime.datetime.now().astimezone().isoformat(timespec='seconds')}")
L.append("")
L.append("## A. 共享库 app_config key=multi_period 收尾复核")
L.append("##    注：cargo test -p web 内含 crates/web/tests/api_multi_period_config.rs，该 binary 会在用例内 PUT/清键（全部落库 enabled=false）⇒ 跑完必须 psql 复核 0 行。")
L.append("$ psql -h 127.0.0.1 -p 5433 -U eestock -d eestock -c \"select key,value from app_config where key='multi_period';\"")
L.append(sh("psql -h 127.0.0.1 -p 5433 -U eestock -d eestock -c \"select key,value from app_config where key='multi_period';\"", {"PGPASSWORD":"eestock"}))
L.append(sh("psql -h 127.0.0.1 -p 5433 -U eestock -d eestock -tAc \"select 'multi_period_rows='||count(*) from app_config where key='multi_period';\"", {"PGPASSWORD":"eestock"}))
L.append("  ⇒ 0 行（键不存在）")
L.append("")
L.append("## B. 未 stage / 未 commit / 未 stash（HEAD 未变）")
L.append("$ git diff --cached --stat"); L.append((sh("git diff --cached --stat") or "  （空）"))
L.append("$ git rev-parse HEAD"); L.append("  " + sh("git rev-parse HEAD") + "  （= 派单 HEAD d6462da）")
L.append("$ git stash list"); L.append((sh("git stash list") or "  （空）"))
L.append("")
L.append("## C. tracked 改动归因（mtime + 车道）")
L.append(sh("git status --porcelain=v1 | grep -E '^ M|^M ' | awk '{print $2}' | while read f; do stat -c '%y %n' \"$f\"; done"))
L.append("  ⇒ 20:26–20:59 的 10 个文件 = P1 车道（后端 dto/rest/lib + 设计文档 + 前端接线）")
L.append("  ⇒ 21:14:53 mock.test.ts / 21:15:01 mock.ts = 本轮 D5-2 车道（mock 口径对齐；+44/−0 与 +92/−0 相对 HEAD，纯新增）")
L.append("$ stat -c '%y %n'（D5-1 新增交付物）")
L.append(sh("stat -c '%y %n' web/src/api/multiPeriodMockParity.test.ts design/15-multi-period/contract-vectors.json crates/web/tests/multi_period_contract_vectors.rs"))
L.append("")
L.append("## D. 线上实例未被触碰（未重启、未发任何请求）")
L.append(sh("ps -o pid,etime,cmd -p 3112540"))
L.append(sh("ss -ltnp 2>/dev/null | grep -E ':808[12]'"))
L.append("  ⇒ PID 3112540 存活、etime ≈9h30m（验收开始时 09:25:33，结束 09:30:42 ⇒ 未重启）")
L.append("  ⇒ 本验收对 8081/8082 **0 请求**（0 写请求；亦未读）⇒ 不干扰线上显示")
L.append("")
L.append("## E. 临时实例/端口/进程收尾（pgrep 用不自匹配写法，且命令外置为脚本以免自匹配）")
L.append("$ pgrep -af '%s'" % PAT)
L.append(sh("pgrep -af '%s'" % PAT) or "  none（无残留 vitest / check-tangle / cargo test / 探针进程）")
L.append("$ ss -ltnp（本机 LISTEN；逐条核对 Owner PID 是否测试进程）")
L.append(sh("ss -ltnp 2>/dev/null | grep -v '127.0.0.53' | grep -E ':808[0-2]|:5433|:1420|:9222|:5037'"))
L.append("  ⇒ listener 归属：8080/8081/8082 = 线上 eestock-app(3112540)、5433 = postgres、1420 = scrylink-web、9222 = chrome、5037 = adb；")
L.append("    无任何 listener 属于测试/探针进程（cargo 集成测试用 127.0.0.1:0 随机端口，进程退出即释放）。")
L.append("  ⇒ 本验收**未自建常驻临时实例**：parity 在纯函数层（真实后端 crate）+ mock 层取证，不需要临时 HTTP 服务 ⇒ 无端口需拆。")
L.append("")
L.append("## F. 仓库文件全程未被修改（向量/实现/沙箱还原校验）")
L.append("$ sha256sum design/15-multi-period/contract-vectors.json"); L.append(sh("sha256sum design/15-multi-period/contract-vectors.json"))
L.append("$ sha256sum web/src/api/mock.ts /tmp/d53_sb/web/src/api/mock.ts"); L.append(sh("sha256sum web/src/api/mock.ts /tmp/d53_sb/web/src/api/mock.ts"))
L.append("$ diff -rq web/src /tmp/d53_sb/web/src（沙箱副本 vs 仓库）"); L.append(sh("diff -rq web/src /tmp/d53_sb/web/src") or "  （无差异）")
L.append("$ sha256sum design/15-multi-period/contract-vectors.json（再次，收尾）"); L.append(sh("sha256sum design/15-multi-period/contract-vectors.json"))
L.append("  ⇒ 变异全部发生在 /tmp 副本；仓库向量/实现 sha256 与验收开始时一致。")
open(EV,'w').write("\n".join(L)+"\n")
print("05_hygiene.txt 全量重写完成")
